---
- name: install projector config
  ansible.builtin.template:
    src: projector.j2
    dest: /etc/nginx/sites-available/projector
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: activate projector config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/projector
    dest: /etc/nginx/sites-enabled/projector
    state: link
    owner: root
    group: root
  notify: restart nginx
