---
- name: install python virtualenv
  hosts: all
  become: yes

  tasks:
    - name: update repositories
      ansible.builtin.apt:
        cache_valid_time: 86400
        update_cache: yes

    - name: install dependencies
      ansible.builtin.apt:
        name:
          - python3-virtualenv
          - less
          - libxext6
          - libxrender1
          - libxtst6
          - libfreetype6
          - libxi6
          - openjdk-11-jdk
        state: present

- name: install python pips
  hosts: all
  tasks:
    - name: install pips
      ansible.builtin.pip:
        name:
          - cryptography
          - projector-installer
        virtualenv: ~/.projectorenv
        virtualenv_command: virtualenv -p python3 --system-site-packages

- name: configure iptables
  hosts: all
  become: yes
  tasks:
    - name: open tcp 9999
      ansible.builtin.iptables:
        action: insert
        chain: INPUT
        protocol: tcp
        destination_port: 9999
        ctstate: NEW
        jump: ACCEPT
        comment: Allow JetBrains Projector communication

    - name: open udp 9999
      ansible.builtin.iptables:
        action: insert
        chain: INPUT
        protocol: udp
        destination_port: 9999
        ctstate: NEW
        jump: ACCEPT
        comment: Allow JetBrains Projector UDP communication

    - name: save iptables
      ansible.builtin.shell:
        cmd: iptables-save > /etc/iptables/rules.v4
