---
- name: install python virtualenv
  hosts: all
  become: yes
  roles:
    - apt
    - iptables
    - fail2ban
    - nginx
    - certbot

- name: install python pips
  hosts: all
  roles:
    - pip
